export type Auditorium = {
  id: string;
  ownerId: string;
  name: string;
  description: string;
  address: string;
  state: string;
  district: string;
  city: string;
  capacity: number;
  dayRate: number;
  amenities: string[];
  images: string[];
  averageRating: number;
  totalReviews: number;
  totalBookings: number;
  status: string;
  approved: boolean;
  isActive: boolean;
  ownerName?: string;
  ownerMobile?: string;
  createdAt: Date;
  updatedAt: Date;
};
